<?php
declare(strict_types=1);
require_once __DIR__ . '/app/includes/layout.php';
$user=require_permission('maintenance');$pdo=db();
function maint_id(mixed $v):int{$id=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return $id===false?0:(int)$id;}
function maint_date(mixed $v):?string{$raw=(string)$v;$d=DateTime::createFromFormat('Y-m-d',$raw);return $d&&$d->format('Y-m-d')===$raw?$raw:null;}
if($_SERVER['REQUEST_METHOD']==='POST'){require_valid_csrf();try{$action=(string)($_POST['action']??'');$id=maint_id($_POST['id']??null);$roomId=maint_id($_POST['room_id']??null)?:null;$assignedTo=maint_id($_POST['assigned_to']??null)?:null;$description=trim((string)($_POST['description']??''));$date=maint_date($_POST['date_reported']??null);$status=(string)($_POST['status']??'pending');if(!in_array($status,['pending','in_progress','resolved'],true)||$description===''||mb_strlen($description)>5000||!$date)throw new RuntimeException('Enter a description, date, and valid status.');if($roomId){$s=$pdo->prepare('SELECT 1 FROM rooms WHERE id=:id');$s->execute(['id'=>$roomId]);if(!$s->fetchColumn())throw new RuntimeException('Select a valid room.');}if($assignedTo){$s=$pdo->prepare("SELECT 1 FROM users WHERE id=:id AND status='active'");$s->execute(['id'=>$assignedTo]);if(!$s->fetchColumn())throw new RuntimeException('Select an active staff member.');}$data=['room_id'=>$roomId,'description'=>$description,'date_reported'=>$date,'status'=>$status,'assigned_to'=>$assignedTo];if($action==='save_maintenance'&&$id>0){$data['id']=$id;$pdo->prepare('UPDATE maintenance_requests SET room_id=:room_id,description=:description,date_reported=:date_reported,status=:status,assigned_to=:assigned_to WHERE id=:id')->execute($data);set_flash('Maintenance request updated.');}elseif($action==='save_maintenance'){$pdo->prepare('INSERT INTO maintenance_requests (room_id,description,date_reported,status,assigned_to) VALUES (:room_id,:description,:date_reported,:status,:assigned_to)')->execute($data);set_flash('Maintenance request added.');}else throw new RuntimeException('Unknown request.');}catch(RuntimeException $e){set_flash($e->getMessage(),'error');}redirect('maintenance.php');}
$action=(string)($_GET['action']??'list');$edit=null;if($action==='edit'){$id=maint_id($_GET['id']??null);$s=$pdo->prepare('SELECT * FROM maintenance_requests WHERE id=:id');$s->execute(['id'=>$id]);$edit=$s->fetch()?:null;if(!$edit){set_flash('Maintenance request not found.','error');redirect('maintenance.php');}}$rooms=$pdo->query('SELECT r.id,r.room_number,d.name dormitory_name FROM rooms r INNER JOIN dormitories d ON d.id=r.dormitory_id ORDER BY d.name,r.room_number')->fetchAll();$staff=$pdo->query("SELECT id,full_name FROM users WHERE status='active' ORDER BY full_name")->fetchAll();$flash=consume_flash();
if(in_array($action,['add','edit'],true)){page_start($action==='edit'?'Update Maintenance':'New Maintenance Request',$user,'maintenance');?>
<p class="eyebrow">Facilities</p><h1><?= $action==='edit'?'Update maintenance request':'New maintenance request'?></h1><?php if($flash):?><p class="flash <?=e($flash['type'])?>"><?=e($flash['message'])?></p><?php endif;?><form method="post" class="panel payment-form"><input type="hidden" name="csrf_token" value="<?=csrf_token()?>"><input type="hidden" name="action" value="save_maintenance"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><label>Room<select name="room_id"><option value="">— General/common area —</option><?php foreach($rooms as $room):?><option value="<?= (int)$room['id']?>" <?= (int)($edit['room_id']??0)===(int)$room['id']?'selected':''?>><?=e($room['dormitory_name'].' — '.$room['room_number'])?></option><?php endforeach;?></select></label><label>Description *<textarea name="description" rows="5" maxlength="5000" required><?=e($edit['description']??'')?></textarea></label><div class="form-grid"><label>Date reported *<input type="date" name="date_reported" value="<?=e($edit['date_reported']??date('Y-m-d'))?>" required></label><label>Status *<select name="status"><?php foreach(['pending'=>'Pending','in_progress'=>'In progress','resolved'=>'Resolved'] as $key=>$label):?><option value="<?=$key?>" <?=($edit['status']??'pending')===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label>Assign to<select name="assigned_to"><option value="">— Unassigned —</option><?php foreach($staff as $member):?><option value="<?= (int)$member['id']?>" <?= (int)($edit['assigned_to']??0)===(int)$member['id']?'selected':''?>><?=e($member['full_name'])?></option><?php endforeach;?></select></label></div><button class="primary" type="submit">Save request</button> <a class="cancel" href="maintenance.php">Cancel</a></form><?php page_end();exit;}
$filter=(string)($_GET['filter']??'open');
if(!in_array($filter,['open','all'],true))$filter='open';
$sql="SELECT m.*,r.room_number,d.name dormitory_name,u.full_name assigned_name FROM maintenance_requests m LEFT JOIN rooms r ON r.id=m.room_id LEFT JOIN dormitories d ON d.id=r.dormitory_id LEFT JOIN users u ON u.id=m.assigned_to".($filter==='open'?" WHERE m.status!='resolved'":'')." ORDER BY FIELD(m.status,'pending','in_progress','resolved'),m.date_reported DESC";
$requests=$pdo->query($sql)->fetchAll();
$maintenanceCounts=['pending'=>0,'in_progress'=>0,'resolved'=>0,'open'=>0,'all'=>0];
foreach($pdo->query('SELECT status,COUNT(*) total FROM maintenance_requests GROUP BY status') as $countRow){$count=(int)$countRow['total'];if(isset($maintenanceCounts[$countRow['status']]))$maintenanceCounts[$countRow['status']]=$count;$maintenanceCounts['all']+=$count;if($countRow['status']!=='resolved')$maintenanceCounts['open']+=$count;}
page_start('Maintenance',$user,'maintenance');?>

<section class="maintenance-hero">
  <div><p class="eyebrow">Facilities</p><h1>Maintenance Requests</h1><p>Track facility issues, assignments, and resolution progress in one place.</p></div>
  <a class="button-link" href="maintenance.php?action=add"><span aria-hidden="true">+</span> New request</a>
</section>

<section class="maintenance-summary-grid" aria-label="Maintenance summary">
  <article><span class="maintenance-summary-icon pending" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg></span><div><span>Pending</span><strong><?=$maintenanceCounts['pending']?></strong></div></article>
  <article><span class="maintenance-summary-icon progress" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M14.7 6.3a4 4 0 0 0-5-5L12 3.6 8.4 7.2 6.1 4.9a4 4 0 0 0 5 5L4 17a2.1 2.1 0 0 0 3 3l7.1-7.1a4 4 0 0 0 5-5l-2.3 2.3-3-3L16.1 5a4 4 0 0 0-1.4 1.3Z"/></svg></span><div><span>In progress</span><strong><?=$maintenanceCounts['in_progress']?></strong></div></article>
  <article><span class="maintenance-summary-icon resolved" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/></svg></span><div><span>Resolved</span><strong><?=$maintenanceCounts['resolved']?></strong></div></article>
</section>

<?php if($flash):?><p class="flash <?=e($flash['type'])?>"><?=e($flash['message'])?></p><?php endif;?>

<section class="panel maintenance-controls">
  <div><p class="eyebrow">Request filters</p><h2>View requests</h2></div>
  <nav class="maintenance-filter-tabs" aria-label="Filter maintenance requests"><a href="maintenance.php?filter=open" class="<?=$filter==='open'?'selected':''?>">Open <span><?=$maintenanceCounts['open']?></span></a><a href="maintenance.php?filter=all" class="<?=$filter==='all'?'selected':''?>">All requests <span><?=$maintenanceCounts['all']?></span></a></nav>
</section>

<section class="panel table-panel maintenance-table">
  <div class="maintenance-table-heading"><div><p class="eyebrow"><?=$filter==='open'?'Active queue':'Complete history'?></p><h2><?=$filter==='open'?'Open maintenance':'All maintenance requests'?></h2></div><span class="count-badge"><?=count($requests)?> request<?=count($requests)===1?'':'s'?></span></div>
  <table><thead><tr><th>Room</th><th>Description</th><th>Reported</th><th>Status</th><th>Assigned</th><th><span class="visually-hidden">Actions</span></th></tr></thead><tbody><?php if(!$requests):?><tr><td colspan="6"><div class="maintenance-empty"><span aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M14.7 6.3a4 4 0 0 0-5-5L12 3.6 8.4 7.2 6.1 4.9a4 4 0 0 0 5 5L4 17a2.1 2.1 0 0 0 3 3l7.1-7.1a4 4 0 0 0 5-5l-2.3 2.3-3-3L16.1 5a4 4 0 0 0-1.4 1.3Z"/></svg></span><div><strong>No maintenance requests found</strong><p>There are no requests in this view.</p></div></div></td></tr><?php else:foreach($requests as $request):?><tr><td><span class="maintenance-room"><?=e($request['dormitory_name']?$request['dormitory_name'].' · '.$request['room_number']:'Common area')?></span></td><td><strong class="maintenance-description"><?=e($request['description'])?></strong></td><td><span class="maintenance-date"><?=e(date('M j, Y',strtotime($request['date_reported'])))?></span></td><td><span class="maintenance-status <?=e($request['status'])?>"><?=e(ucwords(str_replace('_',' ',$request['status'])))?></span></td><td><?php if($request['assigned_name']):preg_match('/^./u',(string)$request['assigned_name'],$assignedInitialMatch);?><div class="maintenance-assignee"><span aria-hidden="true"><?=e(strtoupper($assignedInitialMatch[0]??'?'))?></span><strong><?=e($request['assigned_name'])?></strong></div><?php else:?><span class="not-set">Unassigned</span><?php endif;?></td><td><a class="maintenance-update" href="maintenance.php?action=edit&amp;id=<?=(int)$request['id']?>">Update <span aria-hidden="true">→</span></a></td></tr><?php endforeach;endif;?></tbody></table>
</section>
<?php page_end();
